# Matrices
- Recall indices start from 0

# Scalars and Vectors
- The length of a vector refers to the number of elements in it
- Scalars have 0 dimensions (similar to a point)
- Vectors have 1 dimension (similar to a line)

# Declaring scalars, vectors and matrices

In [1]:
import numpy as np

### Scalars

In [2]:
s = 5
s

5

### Vectors

In [3]:
v = np.array([5, -2, 4])
v

# There is no distinction in numpy between row and column vectors
# There are only n-dimensional arrays

array([ 5, -2,  4])

### Matrices

In [4]:
m = np.array([[5, 12, 6], [-3, 0, 14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data Types

In [5]:
type(s)

int

In [6]:
type(v)

numpy.ndarray

In [7]:
type(m)

numpy.ndarray

In [8]:
s_array = np.array(5)
type(s_array)

# This is another way of creating scalars

numpy.ndarray

### Data Shapes

In [9]:
m.shape

(2, 3)

In [10]:
v.shape

(3,)

In [11]:
v.reshape(1, 3)

array([[ 5, -2,  4]])

In [12]:
v.reshape(3, 1)

array([[ 5],
       [-2],
       [ 4]])

In [13]:
# s.shape returns an error saying 'int has no shape'

s_array.shape

()

# Tensor

- A tensor is the most general concept. A scalar is a rank 0 tensor, a vector is a rank 1 tensor, and a matrix is a rank 2 tensor.
- A tensor of rank 3 can be thought of as a collection of matrices
- Tensors can be stored as arrays and that's how we often deal with the issue

### Creating a tensor

In [14]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [15]:
m2 = np.array([[9, 8, 7], [1, 3, -5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [16]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Checking its shape

In [17]:
t.shape

(2, 2, 3)

### Manually creating a tensor

In [18]:
t_manual = np.array([[[5, 12, 6], [-3, 0, 14]], [[9, 8, 7], [1, 3, -5]]])
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

# Addition and Subtraction of Matrices
- Matrices must have the same dimension for this

In [19]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [20]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [25]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([6, 7, 8, 9, 10])

In [26]:
v1 - v2

array([-5, -5, -5, -5, -5])

In [27]:
v1 + v2

array([ 7,  9, 11, 13, 15])

### Errors when adding

In [28]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [29]:
m1 + 1

# This is adds 1 to each element in m1

array([[ 6, 13,  7],
       [-2,  1, 15]])

# Transpose of a matrix

In [30]:
A = np.array([[5, 12, 6], [-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [31]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

### Transpose of a vector

In [32]:
V = np.array([1, 2, 3])

In [33]:
V.T
# In Python 1D arrays don't really get transposed in the memory of 
# the computer, unless reshaped first

array([1, 2, 3])

In [34]:
V_reshape = V.reshape(1, 3)
V_reshape

array([[1, 2, 3]])

In [35]:
V_reshape.T

array([[1],
       [2],
       [3]])

# Dot Product

In [36]:
v1 = np.array([2, 8, -4])
v2 = np.array([1, -7, 3])

There are two products we can take the dot product (also known as the inner product) or the tensor product (also known as the outer product)

In [38]:
np.dot(v1, v2)

-66

In [45]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])

In [46]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

# Why is Linear Algebra useful?
- Vectorised code
- Image recognition
- Dimensionality Reduction

### Vectorised Code
- This can speed up operations that would've required a loop to complete
- Example: Say the price of a house is equal to 10190 + 223(size) and we have 100 houses to price. 
    - We can do this manually, or with a loop or we can create two matrices.
    - We can create a 5x2 matrix with only 1s in the first column and all the house sizes in the second column and then a 2x1 matrix with 10190 as the first entry and 223 as the second entry.
    - In machine learning these would be the inputs matrix and the weights matrix
- This is a much faster way to compute many values simultaneouly
    
    
### Image recognition
- Deep learning and deep neural networks have been used for image recognition. At the forefront of this are convolutional neural networks (CNNs)
- Famous examples include the MNIST dataset, where the task is to classify handwritten digits. The CIFAR 10 where the task is to classify animals and vehicles. And CIFAR 100 where there are 100 different classes of images.
- Each photo has dimensions, lets say 400x400, each pixel in the photo is a coloured square.
- In a greyscale photo there are 256 shades of grey with white = 0 and black = 255. We can then express the photo as a matrix, each element of the matrix would be a number from 0-255. 
- To represent colour we can use the RGB scale, where the intensity of each colour ranges from 0-255. In order to represent colour photos we use tensors, in this example it would be a 3 x 400 x 400 tensor. This tensor has 3, 400x400 matrices, one for each colour.

### Dimensionality Reduction
- Imagine we have a dataset with 3 variables, in order to represent each point, we use three values one for each variable, x, y, and z. 
- Therefore we are dealing with an mx3 matrix. The point i would correspond to the vector $[x_i, y_i, z_i]$
- In some cases we can find a plane, very close to the data. A plane is 2D and it would be defined by 2 variables, say u and v.
- Not all points would lie on this plane but we can approximately say that they do.
- Linear algebra gives us an efficient way to change our mx3 matrix to an mx2, where the points are represented by the vector $[u_i, v_i]$